config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: @restaurant do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

 <div class="form-group">
    <%= f.label :address %>
    <%= f.text_area :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_area :phone_number, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :category %>
    <%= f.text_area :category, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container mt-5">
  <h1>Edit restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <hr>
  <%= link_to restaurants_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/restaurants/index.html.erb
<h1>  👨🏻‍🍳 My Index 🍽️ </h1>
<div class="container mt-5">
  <ul id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <li>
        <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
        <%= link_to restaurant_path(restaurant.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{restaurant.name}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
  </ul>

  <hr>

  <%= link_to new_restaurant_path do %>
    <i class="fa-solid fa-plus"></i> Add a new restaurant
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h1>New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <hr>
  <%= link_to restaurants_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1><%= @restaurant.name %></h1>
    <%= link_to edit_restaurant_path(@restaurant.id), class: 'btn btn-light btn-sm border' do %>
      <i class="fa fa-pencil"></i> Edit this restaurant
    <% end %>
  </div>

  <p>
 <div class="container mt-5">
  <%= @restaurant.address %><br>
  <%= @restaurant.phone_number %><br>
  <%= @restaurant.category %>
  </p>

  <h2>Reviews : 📝</h2>
  <% @restaurant.reviews.each do |review| %>
    <div class="card mb-3">
      <div class="card-body">
        <p class="card-text"><%= review.rating %> ⭐️</p>
        <p class="card-text"><%= review.content %></p>
      </div>
    </div>
  <% end %>

<div class="container mt-5">
 <h1>Post your Review !</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="form-group">
      <%= f.input :rating %>
    </div>

  <div class="form-group">
      <%= f.input :content %>
    </div>

    <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>
</div>

  <hr>
  <%= link_to restaurants_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>

app/views/reviews/_form.html.erb
<div class="container mt-5">
 <h1>Post your Review !</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="form-group">
      <%= f.input :rating %>
    </div>

  <div class="form-group">
      <%= f.input :content %>
    </div>

    <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>
</div>